### ISSUE TITLE
NoMethodError: undefined method `has_key?' for #<HTTParty::Response:0xb3270e94>

### ISSUE THREAD

**Issue by infused** [mmangino/mogli#30]
This error happens occasionally when talking to Facebook using mogli 0.0.16.  Backtrace follows:

```
[GEM_ROOT]/gems/httparty-0.6.1/lib/httparty/response.rb:59:in `method_missing'
[GEM_ROOT]/gems/mogli-0.0.16/lib/mogli/client.rb:115:in `extract_hash_or_array'
[GEM_ROOT]/gems/mogli-0.0.16/lib/mogli/client.rb:105:in `map_data'
[GEM_ROOT]/gems/mogli-0.0.16/lib/mogli/client.rb:95:in `get_and_map'
[GEM_ROOT]/gems/mogli-0.0.16/lib/mogli/model.rb:130:in `find'
[GEM_ROOT]/gems/mogli-0.0.16/lib/mogli/model.rb:119:in `fetch'
```

**Comment by mmangino** [comment]
Can you add some debugging to get the output returned from the server? That would help me figure out what is going on here.

**Comment by scohen** [comment]
The problem is that HTTParty changed their API after 0.5.2 so that post returns a HTTParty::Response and not a hash. You're gem specifies >= 0.4.2 so when we upgrade bundler updates us to 0.7 of HTTParty, which isn't handled properly.

You can fix your gemfile so that it doesn't upgrade HTTParty past 0.5.2 or handle the response correctly (there's a parsed_response method which returns a hash).

**Comment by mmangino** [comment]
Thanks! Can you try the version from git to see if that works for you?

**Comment by infused** [comment]
The git version is broken because Client#get_and_map contains a debugger statement

**Comment by pomartel** [comment]
Any update on this bug? I'm still getting this exception from time to time.

**Comment by mmangino** [comment]
I thought this was fixed. Can you get me a stack trace?

**Comment by pomartel** [comment]
```
PollsController# (NoMethodError) "undefined method `has_key?' for #<HTTParty::Response:0x002aaab5992458>"
/app/43c24b60-fc06-4362-b112-69866b90c430/home/.bundle/gems/ruby/1.9.1/gems/httparty-0.7.3/lib/httparty/response.rb:76:in `method_missing'
/app/43c24b60-fc06-4362-b112-69866b90c430/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-76a26c8221fb/lib/mogli/client.rb:139:in `is_fetching_array?'
/app/43c24b60-fc06-4362-b112-69866b90c430/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-76a26c8221fb/lib/mogli/client.rb:134:in `extract_hash_or_array'
/app/43c24b60-fc06-4362-b112-69866b90c430/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-76a26c8221fb/lib/mogli/client.rb:123:in `map_data'
/app/43c24b60-fc06-4362-b112-69866b90c430/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-76a26c8221fb/lib/mogli/client.rb:113:in `get_and_map'
/app/43c24b60-fc06-4362-b112-69866b90c430/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-76a26c8221fb/lib/mogli/model.rb:150:in `find'
/app/43c24b60-fc06-4362-b112-69866b90c430/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-76a26c8221fb/lib/mogli/model.rb:135:in `fetch'
/app/43c24b60-fc06-4362-b112-69866b90c430/home/app/controllers/polls_controller.rb:32:in `create'
```

**Comment by mmangino** [comment]
Can you guys check what I just pushed? I think that should fix it.

Mike

**Comment by pomartel** [comment]
I know I can't reproduce the bug myself but I'll send your latest push on a production app and wait and see if I get reports of exceptions. Thanks for taking care of it!

**Comment by pomartel** [comment]
I'm still getting the exception :

```
PollsController# (NoMethodError) "undefined method `has_key?' for #<HTTParty::Response:0x002aaab5992458>"
/app/8d8806eb-3341-4f76-bc2f-9f545c05c90a/home/.bundle/gems/ruby/1.9.1/gems/httparty-0.7.3/lib/httparty/response.rb:76:in `method_missing'
/app/8d8806eb-3341-4f76-bc2f-9f545c05c90a/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-3db4c6e993da/lib/mogli/client.rb:139:in `is_fetching_array?'
/app/8d8806eb-3341-4f76-bc2f-9f545c05c90a/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-3db4c6e993da/lib/mogli/client.rb:134:in `extract_hash_or_array'
/app/8d8806eb-3341-4f76-bc2f-9f545c05c90a/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-3db4c6e993da/lib/mogli/client.rb:123:in `map_data'
/app/8d8806eb-3341-4f76-bc2f-9f545c05c90a/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-3db4c6e993da/lib/mogli/client.rb:113:in `get_and_map'
/app/8d8806eb-3341-4f76-bc2f-9f545c05c90a/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-3db4c6e993da/lib/mogli/model.rb:155:in `find'
/app/8d8806eb-3341-4f76-bc2f-9f545c05c90a/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-3db4c6e993da/lib/mogli/model.rb:135:in `fetch'
/app/8d8806eb-3341-4f76-bc2f-9f545c05c90a/home/app/controllers/polls_controller.rb:32:in `create'
```

**Comment by mmangino** [comment]
Okay,  I spent some time reading the code, and the parsed_response thing is bogus. The HTTParty client delegates anyway. What I think we need to do is to check the reponse code. This new version should raise an HTTPException if Facebook doesn't give a 200. Can you see if that fixes things?

**Comment by pomartel** [comment]
I haven't plan a deployment to my Facebook app this week but I'll let you know if the problem comes back. Thanks for your help fixing this.

**Comment by pomartel** [comment]
Now that I'm rescuing the HTTPException, I get the NoMethodError less often but there still is a case where it happens :
    PollsController# (NoMethodError) "undefined method `has_key?' for #<HTTParty::Response:0x000000058d00b8>"
    /app/0b9ab5f6-06c2-48a8-93b5-c55669163b14/home/.bundle/gems/ruby/1.9.1/gems/httparty-0.7.4/lib/httparty/response.rb:76:in`method_missing'
    /app/0b9ab5f6-06c2-48a8-93b5-c55669163b14/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-468cb88c2fbe/lib/mogli/client.rb:140:in `is_fetching_array?'
    /app/0b9ab5f6-06c2-48a8-93b5-c55669163b14/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-468cb88c2fbe/lib/mogli/client.rb:135:in`extract_hash_or_array'
    /app/0b9ab5f6-06c2-48a8-93b5-c55669163b14/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-468cb88c2fbe/lib/mogli/client.rb:124:in `map_data'
    /app/0b9ab5f6-06c2-48a8-93b5-c55669163b14/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-468cb88c2fbe/lib/mogli/client.rb:114:in`get_and_map'
    /app/0b9ab5f6-06c2-48a8-93b5-c55669163b14/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-468cb88c2fbe/lib/mogli/model.rb:155:in `find'
    /app/0b9ab5f6-06c2-48a8-93b5-c55669163b14/home/.bundle/gems/ruby/1.9.1/bundler/gems/mogli-468cb88c2fbe/lib/mogli/model.rb:135:in`fetch'
    /app/0b9ab5f6-06c2-48a8-93b5-c55669163b14/home/app/controllers/polls_controller.rb:32:in `create'

**Comment by cap10morgan** [comment]
I believe this is the root cause of the bug: https://github.com/jnunemaker/httparty/issues/#issue/71

HTTParty shouldn't be mucking around with Object#respond_to?

It's confusing Mogli.

**Comment by mmangino** [comment]
You're right. Your patch is really close. I'm going to fix it up a bit and I'll send a pull request

**Comment by alexsherstinsky** [comment]
Hi, Mike and others:

I am experiencing a similar issue (with the latest version of mogli and httparty):

undefined method `has_key?' for #<HTTParty::Response:0x000001059a4bf0>
["/Users/shers/.rvm/gems/ruby-1.9.2-p0/gems/httparty-0.7.4/lib/httparty/response.rb:76:in`method_missing'", "/Users/shers/.rvm/gems/ruby-1.9.2-p0/gems/mogli-0.0.27/lib/mogli/client.rb:149:in `is_fetching_array?'", "/Users/shers/.rvm/gems/ruby-1.9.2-p0/gems/mogli-0.0.27/lib/mogli/client.rb:144:in`extract_hash_or_array'", "/Users/shers/.rvm/gems/ruby-1.9.2-p0/gems/mogli-0.0.27/lib/mogli/client.rb:133:in `map_data'", "/Users/shers/.rvm/gems/ruby-1.9.2-p0/gems/mogli-0.0.27/lib/mogli/client.rb:123:in`get_and_map'", "/Users/shers/.rvm/gems/ruby-1.9.2-p0/gems/mogli-0.0.27/lib/mogli/model.rb:155:in `find'"

It happens while trying to look up a Facebook Page object.  It happens only for one Facebook page of the tens of Facebook Pages my code accesses via mogli.  Do you have any news about a possible fix, or any advice for a work around?

Thank you,
--Alex

**Comment by mmangino** [comment]
It's a bug in HTTParty where errors are handled wrong. The HTTParty folks have a patch, but haven't responded to my pull request.

**Comment by alexsherstinsky** [comment]
Got it!  What's the best way to find out when they have released the patched version?

**Comment by mmangino** [comment]
I just check their repo. You should be able to find the pull request.

Mike

**Comment by alexsherstinsky** [comment]
Thanks!

**Comment by alexsherstinsky** [comment]
Hi, Mike:

Would you know if they made the fix available?  I cannot tell for sure, but am not seeing any activity in https://github.com/jnunemaker/httparty/pull/74.

I was wondering if I could get your fix in the mean time.

Thank you,
--Alex

**Comment by alexsherstinsky** [comment]
Hi again, Mike:

I figured out how to get your code -- so I am using your version in my Gemfile as follows:
gem 'httparty', :git => 'git://github.com/mmangino/httparty.git'

However, the NoMethodError exception still occurs:
undefined method `has_key?' for false:FalseClass
["/Users/shers/.rvm/gems/ruby-1.9.2-p0/gems/mogli-0.0.27/lib/mogli/client.rb:149:in`is_fetching_array?'", "/Users/shers/.rvm/gems/ruby-1.9.2-p0/gems/mogli-0.0.27/lib/mogli/client.rb:144:in `extract_hash_or_array'", "/Users/shers/.rvm/gems/ruby-1.9.2-p0/gems/mogli-0.0.27/lib/mogli/client.rb:133:in`map_data'", "/Users/shers/.rvm/gems/ruby-1.9.2-p0/gems/mogli-0.0.27/lib/mogli/client.rb:123:in `get_and_map'", "/Users/shers/.rvm/gems/ruby-1.9.2-p0/gems/mogli-0.0.27/lib/mogli/model.rb:155:in`find'"

Except this time, I do not see httparty in the stack trace.

As before, it happens while trying to look up a Facebook Page object. It happens only for one Facebook page out of tens of Facebook Pages my code accesses via mogli.

Please let me know if you have any ideas for a work-around.

Thank you,
--Alex

**Comment by mmangino** [comment]
Hmm, it looks like parsed_response is returning false in HTTParty. It would be really helpful to get more information about the data including the response body. Can you add some debugging to capture the response, the parsed response and the respone code in these cases? I can't duplicate this, so I have no idea where to start on fixing it.

**Comment by alexsherstinsky** [comment]
Hi, Mike:

Thanks for your reply.  I started working on getting this information.  I am getting somewhere.  I think that there might be a small bug in Mogli (a null pointer).  I will "fix" it and let you know (but I don't think that it will fix the main issue I am facing, which is: HTTParty not returning the Facebook Page Hash (empty, where I know a page exists).  Furthermore, I have a slight suspicion that there is a race condition between Mogli and HTTParty (not sure yet).  I will summarize anything I find.

Thank you,
--Alex

**Comment by alexsherstinsky** [comment]
Hi, Mike:

I submitted a pull request.

However, please ignore (at least for now) my question regarding 'false'
being returned from Open Graph API.  I just tried the same request but with
a valid access_token -- via Mogli::Page.find('allclearid', client) -- and it
worked.  I do not know why a publicly open Facebook Page would require an
access token.

Thank you,
--Alex
P.S.: Still, I would be curious to know if you will accept my pull request.

On Wed, Apr 13, 2011 at 6:17 AM, mmangino <
reply@reply.github.com>wrote:

> Hmm, it looks like parsed_response is returning false in HTTParty. It would
> be really helpful to get more information about the data including the
> response body. Can you add some debugging to capture the response, the
> parsed response and the respone code in these cases? I can't duplicate this,
> so I have no idea where to start on fixing it.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/issues/30#comment_995297

## 

_Alex Sherstinsky_
_V.P. of Product Development
*
*FREEjit_
4000 Westerly Place, Suite 260
Newport Beach, CA 92660
D: (949) 336-4802
M: (650) 260-3913
F:  (949) 209-0370
_asherstinsky@freejit.com_

**Comment by alexsherstinsky** [comment]
Hi again, Mike:

Just in case you might be interested, I think I found the reason why that
particular page returns false: it is a page that lists country restrictions.

#  Here is what Facebook instructs in the Page editing menu:

Entering one or more countries means that only people located in those
countries listed will be able to view your Page. This also means that logged
out users will not be able to see your Page.

# 

Thanks,

--Alex
