### ISSUE TITLE
NoMethodError: undefined method `has_key?' for #<String:0x000000034f30a0>

### ISSUE THREAD

**Issue by Locke23rus** [mmangino/mogli#144]
Worked with `httparty = 0.11.0`, but breaks after upgrading to `0.12.0` 

```
/gems/mogli-0.0.44/lib/mogli/user.rb:11 in "recognize?"
/gems/mogli-0.0.44/lib/mogli/client.rb:235 in "block in determine_class"
/gems/mogli-0.0.44/lib/mogli/client.rb:235 in "each"
/gems/mogli-0.0.44/lib/mogli/client.rb:235 in "detect"
/gems/mogli-0.0.44/lib/mogli/client.rb:235 in "determine_class"
/gems/mogli-0.0.44/lib/mogli/client.rb:214 in "create_instance"
/gems/mogli-0.0.44/lib/mogli/client.rb:209 in "map_to_class"
/gems/mogli-0.0.44/lib/mogli/client.rb:169 in "map_data"
/gems/mogli-0.0.44/lib/mogli/client.rb:153 in "get_and_map"
/gems/mogli-0.0.44/lib/mogli/model.rb:173 in "find"
```

**Comment by shiau** [comment]
Looks like this could be due to https://github.com/jnunemaker/httparty/pull/239

Facebook returns a content-type of `text/javascript; charset=UTF-8` so the call to HTTParty's `Parser` is returning the body as plaintext instead of parsing it as JSON. The error is being thrown because data is now coming in as a JSON string instead of a hash.

**Comment by mmangino** [comment]
It seems like we can check for a string and parse it as JSON, right? That should be a somewhat sane workaround. Anyone interested in submitting a patch?

**Comment by shiau** [comment]
I have a patch in the works. If we set the Accept header to `*/*`, Facebook will return a content type of `application/JSON`. Without it, they send it as `text/javascript`. Currently tying to figure out how to write a test for that.

**Comment by mmangino** [comment]
I’m okay with you just manually testing it.

Mike

**Comment by mmangino** [comment]
I just pushed a new version to address this. Thanks for the fix!
